baseurl = "http://blog.makingdevs.com/"
languageCode = "en-us"
title = "Blog de Making Devs"
theme="hugo-geo"
PygmentsStyle="emacs"
paginate="4"
disqusShortname = "makingdevs"

[permalinks]
post = ":year/:month/:day/:title"

[params]
    showglobe = true

    profilepic = "profile.jpeg"

    github = "https://github.com/makingdevs"
    twitter = "https://twitter.com/makingdevs"
    email = "info@makingdevs.com"

    subtitle = "El código que a veces olvidamos documentar."

    # Nav links below the profile picture
 #  [[params.navlinks]]
 #  name = "Bienvenidos"
 #  url = "2015-04-29-bienvenido-a-makingdevs.md"

